// Shared payload shapes for the API. These mirror the versioned contracts in `contracts/v1`
// and are the only place a response shape is described, so a contract change surfaces here
// rather than in each page that reads it.
export type CaseRow={appointment_id:string;source_patient_id?:string;service_type:string;requested_datetime:string;duration_hours:number;schedule_status:string;delay_days:number|null;real_dataset_status?:string};
export type ScheduleRow={appointment_id:string;service_type:string;status:string;scheduled_datetime:string;scheduled_end_datetime:string;doctors:string|null;nurses:string|null;theatres:string|null;beds:string|null;delay_days:number|null};
export type ExtractionResult={contract_version:string;case_id:string;procedure:string;speciality:string;urgency:string;requested_datetime:string;estimated_duration_minutes:number;maximum_delay_hours:number;required_doctors:string[];required_nurses:number;required_theatre_type:string|null;required_bed_type:string|null;constraints:Record<string,unknown>;confidence:number;human_review_required:boolean;evidence:string[];urgency_confidence:number;urgency_source:string;recommended_time_window_hours:number|null;urgency_evidence:string[];warnings:string[];extractor_version:string};
export type PriorityAssessment={contract_version:string;case_id:string;priority_score:number;priority_level:string;components:Record<string,number>;explanation:string[];policy_version:string;assessed_at:string};
export type WorkflowAllocation={case_id:string;status:'SCHEDULED'|'UNSCHEDULED';rejection_code:string|null;rejection_reason:string|null};
export type WorkflowResult={runId:number;runKey:string;sourceCaseCount:number;resourceCount:number;result:{algorithm:string;solver_status:string;metrics:Record<string,number>;allocations:WorkflowAllocation[]};evaluation:{metrics:Record<string,number>;workload_summary:Record<string,number>}};
export type IntakeReview={id:number;caseId:string;status:'DRAFT'|'REVIEW_REQUIRED'|'APPROVED'|'REJECTED'|'SCHEDULED';case:ExtractionResult;priority:PriorityAssessment|null;noteText:string;serviceCode:string|null;reviewer:string|null;lastRunKey:string|null;lastScheduleStatus:string|null;lastRejectionCode:string|null;lastRejectionReason:string|null;updatedAt:string;audit?:Array<{id:number;actor:string;action:string;createdAt:string}>};
export type ScheduleChange={caseId:string;changeType:string;locked:boolean;previousStart:string|null;nextStart:string|null;shiftMinutes:number|null;resourceChanges:number;rejectionCode:string|null;rejectionReason:string|null};
export type RescheduleResult={baselineRunKey:string;freezeBefore:string;impact:{unchangedCases:number;movedCases:number;droppedCases:number;insertedCases:number;totalShiftMinutes:number;resourceChanges:number;lockedCases:number};changes:ScheduleChange[];workflow:{runKey:string;result:{algorithm:string;solver_status:string}}};
export type ScheduleLock={caseId:string;reason:string;actor:string;createdAt:string;updatedAt:string};
export type ExperimentSummary={algorithmCode:string;scenarioCode:string;caseCount:number;repetitions:number;runtimeMs:number;scheduledCases:number;unscheduledCases:number;theatreUtilisationPercent:number;averageWaitingHours:number;maxWaitingHours:number;emergencyAverageWaitingHours:number;conflictCount:number;hardConstraintViolations:number;jainFairnessIndex:number;continuityMovedCases:number};
export type ExperimentSuite={suite_key:string;suite_type:'COMPARISON'|'ABLATION';source_run_key:string;source_case_count:number;status:string;config_json:Record<string,unknown>|string;summary_json:ExperimentSummary[]|string|null;created_at:string;completed_at:string|null;results:Array<Record<string,unknown>>};
